# Generated by Django 5.0.3 on 2024-04-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannedtrips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedtrip',
            name='trip_number',
        ),
    ]
